name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  detekt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      env:
        GP_KEY: ${{ secrets.GOOGLE_PLAY_SERVICES}}
        
    - name: base64-to-file
      uses: timheuer/base64-to-file@v1.0.4
      with:
        # Name of the file when written to temp location
        fileName: ./app/google_play_services.json
        # The base64 encoded string
        encodedString:  ${{ secrets.GOOGLE_PLAY_SERVICES}}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run detekt
      run: ./gradlew detektAll
    - name: Run unit tests
      run: ./gradlew test
